import type { WorldInput, KnowledgeInput } from '@/engine/content/types'

export const javascriptBasicsWorld: WorldInput = {
  id: 'javascript-basics',
  name: 'The JavaScript Realm',
  description: 'A neon-lit world where variables hold power and functions shape reality.',
  version: '1.0.0',
  theme: {
    biome: 'cyber-city',
    atmosphere: 'cyber',
    backgroundKey: 'bg-cyber',
    musicKey: undefined,
    colorPalette: ['#f5c842', '#4fc3f7', '#ff6b35'],
    environmentEffects: ['neon-glow'],
    difficultyProfile: 'beginner',
  },
  map: {
    layout: 'linear',
    width: 800,
    height: 600,
    connectionStyle: 'line',
    startPosition: { x: 160, y: 460 },
  },
  stages: [
    {
      id: 'stage-1',
      name: 'The Variable Caves',
      position: { x: 160, y: 460 },
      nodeIconKey: 'node-default',
      backgroundKey: 'bg-cyber',
      unlockCondition: { type: 'world_start' },
      hidden: false,
      optional: false,
      boss: {
        id: 'boss-undefined',
        name: 'Lord Undefined',
        spriteKey: 'boss-default',
        introText: 'A shapeless entity appears — it has no name, no value. Lord Undefined thrives when developers forget to declare their variables.',
        defeatText: 'With every variable declared, Lord Undefined weakens. Name your values, engineer!',
        health: 100,
        attackPattern: 'basic',
      },
    },
    {
      id: 'stage-2',
      name: 'The Function Forge',
      position: { x: 380, y: 320 },
      nodeIconKey: 'node-default',
      backgroundKey: 'bg-cyber',
      unlockCondition: { type: 'stage_complete', stageId: 'stage-1' },
      hidden: false,
      optional: false,
      boss: {
        id: 'boss-sideeffect',
        name: 'The Side-Effect Specter',
        spriteKey: 'boss-default',
        introText: 'A ghost that corrupts global state without warning. It mutates, it leaks — it breaks your pure logic.',
        defeatText: 'Pure functions shield you. Write functions that only return — never mutate!',
        health: 120,
        attackPattern: 'basic',
      },
    },
    {
      id: 'stage-3',
      name: 'The Array Archipelago',
      position: { x: 600, y: 200 },
      nodeIconKey: 'node-default',
      backgroundKey: 'bg-cyber',
      unlockCondition: { type: 'stage_complete', stageId: 'stage-2' },
      hidden: false,
      optional: false,
      boss: {
        id: 'boss-outofbounds',
        name: 'The Out-of-Bounds Beast',
        spriteKey: 'boss-default',
        introText: 'It lurks beyond the last index. Access it by mistake and your program crashes.',
        defeatText: 'Zero-indexed mastery! You accessed the right element and slew the beast.',
        health: 140,
        attackPattern: 'basic',
      },
    },
  ],
  npcs: [
    {
      id: 'npc-constara',
      name: 'Constara',
      spriteKey: 'npc-default',
      position: { x: 320, y: 280 },
      role: 'mentor',
      dialogTrigger: 'interact',
      dialogLines: [
        'Welcome to the JavaScript Realm, Forge Engineer.',
        'In this land, all things must be named. Declare your variables wisely.',
        'The Variable Caves to the north hold your first challenge — Lord Undefined awaits.',
      ],
    },
    {
      id: 'npc-archivist',
      name: 'The Archivist',
      spriteKey: 'npc-default',
      position: { x: 560, y: 420 },
      role: 'guide',
      dialogTrigger: 'interact',
      dialogLines: [
        'Ah, you seek the Array Archipelago? Remember: zero-indexed, always.',
        'The first island is index 0. Miss that, and you fall into the void.',
      ],
    },
  ],
  enemies: [
    {
      id: 'enemy-undefined-wisp',
      name: 'Undefined Wisp',
      spriteKey: 'enemy-default',
      encounterStages: ['stage-1'],
      behavior: 'patrol',
      spawnZone: 'variable-caves',
      spawnCount: 2,
      roamRadius: 80,
      encounterType: 'battle',
      linkedChallengeId: 'challenge-1',
    },
    {
      id: 'enemy-sideeffect',
      name: 'Side-Effect Sprite',
      spriteKey: 'enemy-default',
      encounterStages: ['stage-2'],
      behavior: 'chase',
      spawnZone: 'function-forge',
      spawnCount: 2,
      roamRadius: 100,
      encounterType: 'battle',
      linkedChallengeId: 'challenge-2',
    },
    {
      id: 'enemy-outofbounds',
      name: 'OOB Crawler',
      spriteKey: 'enemy-default',
      encounterStages: ['stage-3'],
      behavior: 'patrol',
      spawnZone: 'array-archipelago',
      spawnCount: 3,
      roamRadius: 60,
      encounterType: 'battle',
      linkedChallengeId: 'challenge-3',
    },
  ],
  lore: {
    worldOrigin: 'Long ago, the JavaScript Realm was a land of order. Then Lord Undefined shattered the naming conventions.',
    playerRole: 'You are the last Forge Engineer — restore meaning to the realm.',
    antagonist: 'Lord Undefined, the shapeless terror that appears when values go unnamed.',
  },
  tilemap: {
    tilemapKey: 'world-js-basics',
    tilemapPath: '',
    tilesetKey: '',
    tilesetPath: '',
    spawnPoint: { x: 400, y: 300 },
    tileSize: 16,
    scale: 2,
  },
  zones: [
    {
      id: 'variable-caves',
      name: 'The Variable Caves',
      type: 'dungeon',
      linkedStageId: 'stage-1',
      entranceTile: { x: 5, y: 5 },
      tilemapPath: '',
      bgmKey: '',
      unlockCondition: { type: 'world_start' },
    },
    {
      id: 'function-forge',
      name: 'The Function Forge',
      type: 'dungeon',
      linkedStageId: 'stage-2',
      entranceTile: { x: 42, y: 5 },
      tilemapPath: '',
      bgmKey: '',
      unlockCondition: { type: 'stage_complete', stageId: 'stage-1' },
    },
    {
      id: 'array-archipelago',
      name: 'The Array Archipelago',
      type: 'overworld',
      linkedStageId: 'stage-3',
      entranceTile: { x: 5, y: 30 },
      tilemapPath: '',
      bgmKey: '',
      unlockCondition: { type: 'stage_complete', stageId: 'stage-2' },
    },
  ],
  interactables: [
    {
      id: 'scroll-hoisting',
      type: 'scroll',
      position: { x: 180, y: 200 },
      linkedDiscoveryId: 'discovery-hoisting',
      spriteKey: '',
      glowColor: '#ffdd00',
    },
    {
      id: 'shrine-closures',
      type: 'shrine',
      position: { x: 520, y: 180 },
      linkedDiscoveryId: 'discovery-closures',
      spriteKey: '',
      glowColor: '#cc44ff',
    },
    {
      id: 'chest-spread',
      type: 'chest',
      position: { x: 250, y: 500 },
      linkedDiscoveryId: 'discovery-spread',
      spriteKey: '',
      glowColor: '#ff8800',
    },
  ],
}

export const javascriptBasicsKnowledge: KnowledgeInput = {
  worldId: 'javascript-basics',
  version: '1.0.0',
  topic: 'JavaScript Fundamentals',
  difficultyLevel: 'beginner',
  estimatedHours: 2,
  prerequisites: [],
  stages: [
    {
      stageId: 'stage-1',
      estimatedMinutes: 20,
      prerequisites: [],
      storyIntro: {
        title: 'Into the Variable Caves',
        text: 'You descend into the Variable Caves. The air hums with unnamed values drifting like ghosts. A wise NPC named Constara appears: "In this realm, all things must be named. Declare your first variable, and the caves will remember."',
      },
      concept: {
        title: 'Variables & Constants',
        learningObjective: 'Understand how to declare and use variables in JavaScript',
        chunks: [
          { type: 'text', text: 'A variable is a named container for a value. In JavaScript, you declare variables with `let` or `const`.' },
          { type: 'code', code: 'let playerName = "Forge Engineer";\nconst MAX_LEVEL = 50;\nconsole.log(playerName); // "Forge Engineer"', language: 'javascript' },
          { type: 'text', text: 'Use `const` for values that never change. Use `let` for values that may be reassigned. Avoid `var` — it has confusing scoping rules.' },
          { type: 'code', code: 'let score = 0;\nscore = score + 10; // OK with let\n\nconst hp = 100;\n// hp = 50; // Error! const cannot be reassigned', language: 'javascript' },
        ],
      },
      quests: [
        {
          id: 'quest-1-1',
          type: 'code-task',
          title: 'Name the Nameless',
          objective: 'Declare a const named `hero` with any string value.',
          hints: ['Use the `const` keyword followed by the variable name.'],
          validation: { strategy: 'includes', pattern: 'const hero', successMessage: 'Variable declared!', failureMessage: 'Make sure to use `const hero = ...`' },
        },
      ],
      challenge: {
        id: 'challenge-1',
        type: 'mcq',
        adaptiveDifficulty: true,
        variants: {
          easy: [
            {
              id: 'q1-easy-1',
              text: 'Which keyword creates a variable that CANNOT be reassigned?',
              options: ['var', 'let', 'const', 'set'],
              correctIndex: 2,
              explanation: '`const` declares a constant — once assigned, it cannot be reassigned.',
            },
          ],
          medium: [
            {
              id: 'q1-med-1',
              text: 'Which keyword creates a variable that CANNOT be reassigned?',
              options: ['var', 'let', 'const', 'set'],
              correctIndex: 2,
              explanation: '`const` declares a constant — once assigned, it cannot be reassigned.',
            },
            {
              id: 'q1-med-2',
              text: 'What will `console.log(typeof undefined)` print?',
              options: ['"null"', '"undefined"', '"object"', '"void"'],
              correctIndex: 1,
              explanation: '`typeof undefined` returns the string `"undefined"`.',
            },
          ],
          hard: [
            {
              id: 'q1-hard-1',
              text: 'Which keyword creates a variable that CANNOT be reassigned?',
              options: ['var', 'let', 'const', 'set'],
              correctIndex: 2,
              explanation: '`const` declares a constant — once assigned, it cannot be reassigned.',
            },
            {
              id: 'q1-hard-2',
              text: 'What will `console.log(typeof undefined)` print?',
              options: ['"null"', '"undefined"', '"object"', '"void"'],
              correctIndex: 1,
              explanation: '`typeof undefined` returns the string `"undefined"`.',
            },
            {
              id: 'q1-hard-3',
              text: 'Which is a valid variable declaration?',
              options: ['variable name = 5', 'let 1name = 5', 'const name = 5', 'set name = 5'],
              correctIndex: 2,
              explanation: '`const name = 5` is valid. Variable names cannot start with a number.',
            },
          ],
        },
      },
      xpReward: 150,
      bossObjective: {
        title: 'Defeat Lord Undefined',
        description: 'Declare both a `let` variable and a `const` constant in a single code block.',
        completionCondition: 'quest_complete',
        victoryText: 'Lord Undefined has been named into submission!',
      },
      skills: ['variables', 'constants'],
    },
    {
      stageId: 'stage-2',
      estimatedMinutes: 25,
      prerequisites: ['stage-1'],
      storyIntro: {
        title: 'The Function Forge',
        text: 'You reach the Function Forge. Sparks fly as master smiths hammer out reusable actions. "A function," says the Forge Master, "captures logic so it can be called again and again. Without functions, every warrior must relearn every skill from scratch."',
      },
      concept: {
        title: 'Functions',
        learningObjective: 'Define and call functions in JavaScript using both traditional and arrow syntax',
        chunks: [
          { type: 'text', text: 'A function is a reusable block of code. You define it once and call it multiple times.' },
          { type: 'code', code: 'function greet(name) {\n  return `Hello, ${name}!`;\n}\n\nconsole.log(greet("Forge Engineer")); // "Hello, Forge Engineer!"', language: 'javascript' },
          { type: 'text', text: 'Arrow functions are a shorter syntax, especially useful for callbacks.' },
          { type: 'code', code: 'const greet = (name) => `Hello, ${name}!`;\n\n// Multi-line arrow function\nconst add = (a, b) => {\n  return a + b;\n};', language: 'javascript' },
        ],
      },
      quests: [
        {
          id: 'quest-2-1',
          type: 'code-task',
          title: 'Forge a Function',
          objective: 'Write a function named `add` that returns the sum of two parameters.',
          hints: ['Use `function add(a, b) { ... }` or `const add = (a, b) => ...`'],
          validation: { strategy: 'regex', pattern: '(function\\s+add|const\\s+add\\s*=)', successMessage: 'Function forged!', failureMessage: 'Name your function `add`.' },
        },
      ],
      challenge: {
        id: 'challenge-2',
        type: 'mcq',
        adaptiveDifficulty: true,
        variants: {
          easy: [
            {
              id: 'q2-easy-1',
              text: 'What does a function return if it has no `return` statement?',
              options: ['0', 'null', 'undefined', 'false'],
              correctIndex: 2,
              explanation: 'Functions without a `return` statement implicitly return `undefined`.',
            },
          ],
          medium: [
            {
              id: 'q2-med-1',
              text: 'What does a function return if it has no `return` statement?',
              options: ['0', 'null', 'undefined', 'false'],
              correctIndex: 2,
              explanation: 'Functions without a `return` statement implicitly return `undefined`.',
            },
            {
              id: 'q2-med-2',
              text: 'Which is an arrow function?',
              options: ['function() => {}', 'const f = () => {}', 'arrow f() {}', '=> function f() {}'],
              correctIndex: 1,
              explanation: 'Arrow function syntax: `const name = (params) => expression`.',
            },
          ],
          hard: [
            {
              id: 'q2-hard-1',
              text: 'What does a function return if it has no `return` statement?',
              options: ['0', 'null', 'undefined', 'false'],
              correctIndex: 2,
              explanation: 'Functions without a `return` statement implicitly return `undefined`.',
            },
            {
              id: 'q2-hard-2',
              text: 'Which is an arrow function?',
              options: ['function() => {}', 'const f = () => {}', 'arrow f() {}', '=> function f() {}'],
              correctIndex: 1,
              explanation: 'Arrow function syntax: `const name = (params) => expression`.',
            },
            {
              id: 'q2-hard-3',
              text: 'What is a "pure function"?',
              options: ['A function with no parameters', 'A function that always returns the same output for the same input with no side effects', 'A function written with arrow syntax', 'A function that calls itself'],
              correctIndex: 1,
              explanation: 'Pure functions are predictable and side-effect free.',
            },
          ],
        },
      },
      xpReward: 200,
      bossObjective: {
        title: 'Defeat the Side-Effect Specter',
        description: 'Write a pure function that takes two numbers and returns their product.',
        completionCondition: 'quest_complete',
        victoryText: 'The specter dissolves — your function is pure!',
      },
      skills: ['functions', 'arrow-functions'],
    },
    {
      stageId: 'stage-3',
      estimatedMinutes: 30,
      prerequisites: ['stage-2'],
      storyIntro: {
        title: 'The Array Archipelago',
        text: 'The Array Archipelago stretches before you — islands of ordered data. "Each island is an index," the Archivist explains. "Arrays are zero-indexed. The first island is index 0. Miss that, and you fall into the void."',
      },
      concept: {
        title: 'Arrays',
        learningObjective: 'Create and manipulate arrays using common array methods',
        chunks: [
          { type: 'text', text: 'An array is an ordered list of values. Arrays are zero-indexed — the first element is at index 0.' },
          { type: 'code', code: 'const heroes = ["knight", "mage", "archer"];\nconsole.log(heroes[0]); // "knight"\nconsole.log(heroes.length); // 3', language: 'javascript' },
          { type: 'text', text: 'Common array methods: `push` adds to the end, `pop` removes from the end, `map` transforms each element, `filter` keeps matching elements.' },
          { type: 'code', code: 'const xp = [100, 200, 150, 300];\nconst doubled = xp.map(x => x * 2);   // [200, 400, 300, 600]\nconst high = xp.filter(x => x > 150); // [200, 300]', language: 'javascript' },
        ],
      },
      quests: [
        {
          id: 'quest-3-1',
          type: 'code-task',
          title: 'Chart the Islands',
          objective: 'Create an array named `islands` with at least 3 string elements.',
          hints: ['Use square brackets: `const islands = ["a", "b", "c"]`'],
          validation: { strategy: 'regex', pattern: 'const\\s+islands\\s*=\\s*\\[', successMessage: 'Islands charted!', failureMessage: 'Declare `const islands = [...]`' },
        },
      ],
      challenge: {
        id: 'challenge-3',
        type: 'mcq',
        adaptiveDifficulty: true,
        variants: {
          easy: [
            {
              id: 'q3-easy-1',
              text: 'What is the index of the FIRST element in a JavaScript array?',
              options: ['1', '-1', '0', 'undefined'],
              correctIndex: 2,
              explanation: 'JavaScript arrays are zero-indexed. The first element is always at index 0.',
            },
          ],
          medium: [
            {
              id: 'q3-med-1',
              text: 'What is the index of the FIRST element in a JavaScript array?',
              options: ['1', '-1', '0', 'undefined'],
              correctIndex: 2,
              explanation: 'JavaScript arrays are zero-indexed.',
            },
            {
              id: 'q3-med-2',
              text: 'Which method adds an element to the END of an array?',
              options: ['append()', 'push()', 'add()', 'insert()'],
              correctIndex: 1,
              explanation: '`Array.push(value)` adds one or more elements to the end.',
            },
          ],
          hard: [
            {
              id: 'q3-hard-1',
              text: 'What is the index of the FIRST element in a JavaScript array?',
              options: ['1', '-1', '0', 'undefined'],
              correctIndex: 2,
              explanation: 'JavaScript arrays are zero-indexed.',
            },
            {
              id: 'q3-hard-2',
              text: 'Which method adds an element to the END of an array?',
              options: ['append()', 'push()', 'add()', 'insert()'],
              correctIndex: 1,
              explanation: '`Array.push(value)` adds one or more elements to the end.',
            },
            {
              id: 'q3-hard-3',
              text: 'What does `[1, 2, 3].map(x => x * 2)` return?',
              options: ['[1, 2, 3]', '[2, 4, 6]', '6', '[3, 4, 5]'],
              correctIndex: 1,
              explanation: '`map` creates a new array by applying the function to each element.',
            },
          ],
        },
      },
      xpReward: 250,
      bossObjective: {
        title: 'Defeat the Out-of-Bounds Beast',
        description: 'Use `filter` on an array of numbers to keep only values greater than 10.',
        completionCondition: 'quest_complete',
        victoryText: 'Zero-indexed mastery achieved!',
      },
      skills: ['arrays', 'array-methods'],
    },
  ],
  skillTree: { nodes: [] },
  discoveries: [
    {
      id: 'discovery-hoisting',
      title: 'The Secret of Hoisting',
      type: 'scroll',
      xpReward: 25,
      coinReward: 10,
      content: {
        type: 'text',
        text: 'JavaScript "hoists" `var` declarations to the top of their scope — but not their values. This is why accessing a `var` before assignment gives `undefined` instead of an error. Use `let` and `const` to avoid this confusion.',
      },
    },
    {
      id: 'discovery-closures',
      title: 'Closure Shrine',
      type: 'shrine',
      xpReward: 50,
      coinReward: 25,
      content: {
        type: 'code',
        code: `function makeCounter() {\n  let count = 0;\n  return () => ++count;\n}\n\nconst counter = makeCounter();\nconsole.log(counter()); // 1\nconsole.log(counter()); // 2`,
        language: 'javascript',
        caption: 'A closure "closes over" variables in its outer scope — they persist between calls.',
      },
    },
    {
      id: 'discovery-spread',
      title: 'Treasure: Spread Operator',
      type: 'chest',
      xpReward: 30,
      coinReward: 15,
      content: {
        type: 'code',
        code: `const a = [1, 2, 3];\nconst b = [...a, 4, 5]; // [1, 2, 3, 4, 5]\n\nconst obj = { x: 1 };\nconst obj2 = { ...obj, y: 2 }; // { x: 1, y: 2 }`,
        language: 'javascript',
        caption: 'The spread operator (...) unpacks iterables into a new array or object.',
      },
    },
  ],
}
