import type { WorldInput, KnowledgeInput } from '@/engine/content/types'

export const kubernetesBasicsWorld: WorldInput = {
  id: 'kubernetes-basics',
  name: 'The Kubernetes Citadel',
  description: 'A vast fortress where containers are orchestrated across many nodes.',
  version: '1.0.0',
  theme: {
    biome: 'orbital-station',
    atmosphere: 'space',
    backgroundKey: 'bg-space',
    musicKey: undefined,
    colorPalette: ['#4fc3f7', '#ff6b35', '#4ade80'],
    environmentEffects: ['stars'],
    difficultyProfile: 'intermediate',
  },
  map: {
    layout: 'linear',
    width: 800,
    height: 600,
    connectionStyle: 'line',
    startPosition: { x: 160, y: 460 },
  },
  stages: [
    {
      id: 'stage-1',
      name: 'The Pod Foundry',
      position: { x: 160, y: 460 },
      nodeIconKey: 'node-default',
      backgroundKey: 'bg-space',
      unlockCondition: { type: 'world_start' },
      hidden: false,
      optional: false,
      boss: {
        id: 'boss-crashloop',
        name: 'CrashLoopBackOff',
        spriteKey: 'boss-default',
        introText: 'A pod that restarts endlessly, consuming resources and hope. It loops, it crashes, it loops again.',
        defeatText: 'You identified the misconfiguration. The pod stabilizes — the loop is broken!',
        health: 100,
        attackPattern: 'basic',
      },
    },
    {
      id: 'stage-2',
      name: 'The Deployment Citadel',
      position: { x: 380, y: 320 },
      nodeIconKey: 'node-default',
      backgroundKey: 'bg-space',
      unlockCondition: { type: 'stage_complete', stageId: 'stage-1' },
      hidden: false,
      optional: false,
      boss: {
        id: 'boss-imagepull',
        name: 'ImagePullBackOff',
        spriteKey: 'boss-default',
        introText: 'Guards the gates with broken image references. Containers cannot start when the image cannot be pulled.',
        defeatText: 'The correct image reference is set. Containers are pulling and starting!',
        health: 120,
        attackPattern: 'basic',
      },
    },
    {
      id: 'stage-3',
      name: 'The Service Nexus',
      position: { x: 600, y: 200 },
      nodeIconKey: 'node-default',
      backgroundKey: 'bg-space',
      unlockCondition: { type: 'stage_complete', stageId: 'stage-2' },
      hidden: false,
      optional: false,
      boss: {
        id: 'boss-noendpoints',
        name: 'The No-Endpoints Phantom',
        spriteKey: 'boss-default',
        introText: 'Services that connect to nothing. Label selector mismatches lurk here, leaving your service routing to void.',
        defeatText: 'Labels aligned! The endpoints populate — traffic flows again.',
        health: 140,
        attackPattern: 'basic',
      },
    },
  ],
  npcs: [
    {
      id: 'npc-herald',
      name: 'Cluster Herald',
      spriteKey: 'npc-default',
      position: { x: 320, y: 280 },
      role: 'guide',
      dialogTrigger: 'interact',
      dialogLines: [
        'Welcome, SRE Paladin. The Citadel is in chaos.',
        'CrashLoopBackOff has seized the Pod Foundry. Start there.',
        'WASD to move. E to interact with scrolls and shrines.',
      ],
    },
    {
      id: 'npc-sre-veteran',
      name: 'SRE Veteran',
      spriteKey: 'npc-default',
      position: { x: 560, y: 400 },
      role: 'mentor',
      dialogTrigger: 'interact',
      dialogLines: [
        'Labels are the language of Kubernetes. Services speak nothing else.',
        'A selector that matches no pod creates silence — no endpoints, no traffic.',
      ],
    },
  ],
  enemies: [
    {
      id: 'enemy-crashloop',
      name: 'CrashLoop Drone',
      spriteKey: 'enemy-default',
      encounterStages: ['stage-1'],
      behavior: 'patrol',
      spawnZone: 'pod-foundry',
      spawnCount: 2,
      roamRadius: 80,
      encounterType: 'battle',
      linkedChallengeId: 'challenge-1',
    },
    {
      id: 'enemy-imagepull',
      name: 'ImagePull Ghost',
      spriteKey: 'enemy-default',
      encounterStages: ['stage-2'],
      behavior: 'chase',
      spawnZone: 'deployment-citadel',
      spawnCount: 2,
      roamRadius: 100,
      encounterType: 'battle',
      linkedChallengeId: 'challenge-2',
    },
    {
      id: 'enemy-noendpoints',
      name: 'No-Endpoint Shade',
      spriteKey: 'enemy-default',
      encounterStages: ['stage-3'],
      behavior: 'patrol',
      spawnZone: 'service-nexus',
      spawnCount: 3,
      roamRadius: 60,
      encounterType: 'battle',
      linkedChallengeId: 'challenge-3',
    },
  ],
  lore: {
    worldOrigin: 'The Kubernetes Citadel once ran flawlessly — every container in its place, every service routing true. Then the Great Misconfiguration struck.',
    playerRole: 'You are the SRE Paladin. Restore the cluster to operational status.',
    antagonist: 'CrashLoopBackOff — the endless restart cycle that drains cluster resources.',
  },
  tilemap: {
    tilemapKey: 'world-k8s-basics',
    tilemapPath: '',
    tilesetKey: '',
    tilesetPath: '',
    spawnPoint: { x: 400, y: 300 },
    tileSize: 16,
    scale: 2,
  },
  zones: [
    {
      id: 'pod-foundry',
      name: 'Pod Foundry',
      type: 'dungeon',
      linkedStageId: 'stage-1',
      entranceTile: { x: 5, y: 5 },
      tilemapPath: '',
      bgmKey: '',
      unlockCondition: { type: 'world_start' },
    },
    {
      id: 'deployment-citadel',
      name: 'Deployment Citadel',
      type: 'dungeon',
      linkedStageId: 'stage-2',
      entranceTile: { x: 42, y: 5 },
      tilemapPath: '',
      bgmKey: '',
      unlockCondition: { type: 'stage_complete', stageId: 'stage-1' },
    },
    {
      id: 'service-nexus',
      name: 'Service Nexus',
      type: 'dungeon',
      linkedStageId: 'stage-3',
      entranceTile: { x: 5, y: 30 },
      tilemapPath: '',
      bgmKey: '',
      unlockCondition: { type: 'stage_complete', stageId: 'stage-2' },
    },
  ],
  interactables: [
    {
      id: 'scroll-pod-anatomy',
      type: 'scroll',
      position: { x: 180, y: 200 },
      linkedDiscoveryId: 'discovery-pod-anatomy',
      spriteKey: '',
      glowColor: '#ffdd00',
    },
    {
      id: 'shrine-labels',
      type: 'shrine',
      position: { x: 520, y: 180 },
      linkedDiscoveryId: 'discovery-label-selectors',
      spriteKey: '',
      glowColor: '#4fc3f7',
    },
    {
      id: 'chest-rolling-update',
      type: 'chest',
      position: { x: 250, y: 500 },
      linkedDiscoveryId: 'discovery-rolling-update',
      spriteKey: '',
      glowColor: '#ff8800',
    },
  ],
}

export const kubernetesBasicsKnowledge: KnowledgeInput = {
  worldId: 'kubernetes-basics',
  version: '1.0.0',
  topic: 'Kubernetes Fundamentals',
  difficultyLevel: 'intermediate',
  estimatedHours: 3,
  prerequisites: ['Docker basics', 'Basic CLI usage'],
  stages: [
    {
      stageId: 'stage-1',
      estimatedMinutes: 25,
      prerequisites: [],
      storyIntro: {
        title: 'The Pod Foundry',
        text: 'You enter the Pod Foundry. Steam rises from massive forges where workers create the smallest deployable unit: the Pod. "A Pod wraps one or more containers," the Forge Warden explains. "They share a network and storage. Master Pods, and you master the foundation."',
      },
      concept: {
        title: 'Pods — The Smallest Deployable Unit',
        learningObjective: 'Understand what Pods are and how to work with them using kubectl',
        chunks: [
          { type: 'text', text: 'A **Pod** is the smallest deployable unit in Kubernetes. It wraps one or more containers that share network and storage resources.' },
          { type: 'code', code: 'apiVersion: v1\nkind: Pod\nmetadata:\n  name: my-pod\nspec:\n  containers:\n  - name: app\n    image: nginx:latest\n    ports:\n    - containerPort: 80', language: 'yaml' },
          { type: 'text', text: 'Pods are ephemeral — they are not self-healing. If a Pod dies, it is gone. Use Deployments to manage Pod lifecycle.' },
          { type: 'code', code: '# Common kubectl Pod commands\nkubectl get pods\nkubectl describe pod my-pod\nkubectl logs my-pod\nkubectl delete pod my-pod', language: 'bash' },
        ],
      },
      quests: [
        {
          id: 'quest-1-1',
          type: 'fill-blank',
          title: 'Define a Pod',
          objective: 'What is the `kind` field value for a Pod manifest?',
          hints: ['It matches the Kubernetes resource type name.'],
          validation: { strategy: 'exact', pattern: 'Pod', successMessage: 'Correct!', failureMessage: 'The kind is exactly "Pod" (capital P).' },
        },
      ],
      challenge: {
        id: 'challenge-1',
        type: 'mcq',
        adaptiveDifficulty: true,
        variants: {
          easy: [
            {
              id: 'q1-easy-1',
              text: 'What is the smallest deployable unit in Kubernetes?',
              options: ['Container', 'Pod', 'Node', 'Deployment'],
              correctIndex: 1,
              explanation: 'A Pod is the smallest deployable unit. It wraps containers.',
            },
          ],
          medium: [
            {
              id: 'q1-med-1',
              text: 'What is the smallest deployable unit in Kubernetes?',
              options: ['Container', 'Pod', 'Node', 'Deployment'],
              correctIndex: 1,
              explanation: 'A Pod is the smallest deployable unit.',
            },
            {
              id: 'q1-med-2',
              text: 'Why are Pods considered ephemeral?',
              options: ['They auto-scale indefinitely', 'They cannot run containers', 'When a Pod dies it is not restarted unless managed by a controller', 'They run only once per cluster'],
              correctIndex: 2,
              explanation: 'Pods alone do not self-heal. Controllers like Deployments manage Pod restarts.',
            },
          ],
          hard: [
            {
              id: 'q1-hard-1',
              text: 'What is the smallest deployable unit in Kubernetes?',
              options: ['Container', 'Pod', 'Node', 'Deployment'],
              correctIndex: 1,
              explanation: 'A Pod is the smallest deployable unit.',
            },
            {
              id: 'q1-hard-2',
              text: 'Why are Pods considered ephemeral?',
              options: ['They auto-scale indefinitely', 'They cannot run containers', 'When a Pod dies it is not restarted unless managed by a controller', 'They run only once per cluster'],
              correctIndex: 2,
              explanation: 'Pods alone do not self-heal.',
            },
            {
              id: 'q1-hard-3',
              text: 'Which kubectl command shows logs for a Pod?',
              options: ['kubectl get pod', 'kubectl describe pod', 'kubectl logs pod-name', 'kubectl exec pod-name'],
              correctIndex: 2,
              explanation: '`kubectl logs <pod-name>` streams the container logs.',
            },
          ],
        },
      },
      xpReward: 150,
      bossObjective: {
        title: 'Defeat CrashLoopBackOff',
        description: 'Explain in your own words why you should NOT run bare Pods in production.',
        completionCondition: 'quest_complete',
        victoryText: 'CrashLoopBackOff dissolves — Pods are now properly managed!',
      },
      skills: ['pods', 'kubectl-basics'],
    },
    {
      stageId: 'stage-2',
      estimatedMinutes: 30,
      prerequisites: ['stage-1'],
      storyIntro: {
        title: 'The Deployment Citadel',
        text: '"A single Pod is a single point of failure," the Deployment Architect warns you. "A Deployment declares desired state — how many replicas, which image, how to roll out updates. The cluster fights to maintain that state forever."',
      },
      concept: {
        title: 'Deployments & ReplicaSets',
        learningObjective: 'Create and manage Deployments to maintain Pod replicas',
        chunks: [
          { type: 'text', text: 'A **Deployment** manages a ReplicaSet, which ensures a specified number of Pod replicas are running at all times.' },
          { type: 'code', code: 'apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: web-app\nspec:\n  replicas: 3\n  selector:\n    matchLabels:\n      app: web-app\n  template:\n    metadata:\n      labels:\n        app: web-app\n    spec:\n      containers:\n      - name: app\n        image: myapp:v1.0', language: 'yaml' },
          { type: 'text', text: 'Rolling updates replace Pods gradually. If the new version fails, roll back: `kubectl rollout undo deployment/web-app`.' },
          { type: 'code', code: '# Scale, status, rollback\nkubectl scale deployment web-app --replicas=5\nkubectl rollout status deployment/web-app\nkubectl rollout undo deployment/web-app', language: 'bash' },
        ],
      },
      quests: [
        {
          id: 'quest-2-1',
          type: 'fill-blank',
          title: 'Set the Replica Count',
          objective: 'In a Deployment spec, what field controls the number of Pod replicas?',
          hints: ['It is a top-level field in `spec`.'],
          validation: { strategy: 'exact', pattern: 'replicas', successMessage: 'Correct!', failureMessage: 'The field is called `replicas`.' },
        },
      ],
      challenge: {
        id: 'challenge-2',
        type: 'mcq',
        adaptiveDifficulty: true,
        variants: {
          easy: [
            {
              id: 'q2-easy-1',
              text: 'What does a Deployment\'s `selector.matchLabels` do?',
              options: ['Selects the nodes where Pods run', 'Matches the labels on Pods the Deployment manages', 'Filters which namespaces are used', 'Sets resource limits on Pods'],
              correctIndex: 1,
              explanation: 'The selector tells the Deployment which Pods it owns, matched by label.',
            },
          ],
          medium: [
            {
              id: 'q2-med-1',
              text: 'What does a Deployment\'s `selector.matchLabels` do?',
              options: ['Selects the nodes where Pods run', 'Matches the labels on Pods the Deployment manages', 'Filters which namespaces are used', 'Sets resource limits on Pods'],
              correctIndex: 1,
              explanation: 'The selector tells the Deployment which Pods it owns.',
            },
            {
              id: 'q2-med-2',
              text: 'What happens during a rolling update?',
              options: ['All old Pods are deleted before new ones start', 'The cluster restarts', 'New Pods are gradually created while old ones are terminated', 'The deployment is paused'],
              correctIndex: 2,
              explanation: 'Rolling updates replace Pods incrementally, maintaining availability.',
            },
          ],
          hard: [
            {
              id: 'q2-hard-1',
              text: 'What does a Deployment\'s `selector.matchLabels` do?',
              options: ['Selects the nodes where Pods run', 'Matches the labels on Pods the Deployment manages', 'Filters which namespaces are used', 'Sets resource limits on Pods'],
              correctIndex: 1,
              explanation: 'The selector tells the Deployment which Pods it owns.',
            },
            {
              id: 'q2-hard-2',
              text: 'What happens during a rolling update?',
              options: ['All old Pods are deleted before new ones start', 'The cluster restarts', 'New Pods are gradually created while old ones are terminated', 'The deployment is paused'],
              correctIndex: 2,
              explanation: 'Rolling updates replace Pods incrementally.',
            },
            {
              id: 'q2-hard-3',
              text: 'Which command rolls back a Deployment to its previous version?',
              options: ['kubectl revert deployment/web-app', 'kubectl rollout undo deployment/web-app', 'kubectl reset deployment/web-app', 'kubectl rollback deployment/web-app'],
              correctIndex: 1,
              explanation: '`kubectl rollout undo deployment/<name>` reverts to the previous revision.',
            },
          ],
        },
      },
      xpReward: 200,
      bossObjective: {
        title: 'Defeat ImagePullBackOff',
        description: 'Describe the difference between a ReplicaSet and a Deployment in your own words.',
        completionCondition: 'quest_complete',
        victoryText: 'The image reference is fixed. Containers are running!',
      },
      skills: ['deployments', 'replicasets', 'rolling-updates'],
    },
    {
      stageId: 'stage-3',
      estimatedMinutes: 30,
      prerequisites: ['stage-2'],
      storyIntro: {
        title: 'The Service Nexus',
        text: '"Pods come and go," the Network Sage explains, "but a Service gives them a stable address. Label selectors are the key — a Service finds its Pods by matching labels. Misconfigure the labels, and the Service connects to nothing."',
      },
      concept: {
        title: 'Services & Networking',
        learningObjective: 'Expose Pods using Kubernetes Services and understand label-selector matching',
        chunks: [
          { type: 'text', text: 'A **Service** provides a stable IP and DNS name for a set of Pods, selected by labels. Even as Pods are created and destroyed, the Service endpoint stays the same.' },
          { type: 'code', code: 'apiVersion: v1\nkind: Service\nmetadata:\n  name: web-service\nspec:\n  selector:\n    app: web-app    # must match Pod labels\n  ports:\n  - port: 80\n    targetPort: 8080\n  type: ClusterIP', language: 'yaml' },
          { type: 'text', text: 'Service types: **ClusterIP** (internal only), **NodePort** (on each node\'s IP), **LoadBalancer** (cloud LB).' },
          { type: 'code', code: '# Inspect endpoints\nkubectl get endpoints web-service\n# If <none>, labels are mismatched\nkubectl describe service web-service', language: 'bash' },
        ],
      },
      quests: [
        {
          id: 'quest-3-1',
          type: 'fill-blank',
          title: 'Name the Default Service Type',
          objective: 'What is the default Service type in Kubernetes (only accessible within the cluster)?',
          hints: ['It is also the name of the cluster-internal IP.'],
          validation: { strategy: 'exact', pattern: 'ClusterIP', successMessage: 'Correct!', failureMessage: 'The default type is `ClusterIP`.' },
        },
      ],
      challenge: {
        id: 'challenge-3',
        type: 'mcq',
        adaptiveDifficulty: true,
        variants: {
          easy: [
            {
              id: 'q3-easy-1',
              text: 'A Service shows `<none>` under ENDPOINTS. What is the most likely cause?',
              options: ['The Service port is wrong', 'The Service selector does not match any Pod labels', 'No nodes are available', 'The namespace is missing'],
              correctIndex: 1,
              explanation: 'When selectors do not match Pod labels, no Pods are registered as endpoints.',
            },
          ],
          medium: [
            {
              id: 'q3-med-1',
              text: 'A Service shows `<none>` under ENDPOINTS. What is the most likely cause?',
              options: ['The Service port is wrong', 'The Service selector does not match any Pod labels', 'No nodes are available', 'The namespace is missing'],
              correctIndex: 1,
              explanation: 'When selectors do not match Pod labels, no Pods are registered.',
            },
            {
              id: 'q3-med-2',
              text: 'Which Service type exposes the service on every node\'s IP at a static port?',
              options: ['ClusterIP', 'LoadBalancer', 'NodePort', 'ExternalName'],
              correctIndex: 2,
              explanation: 'NodePort allocates a port (30000–32767) on every cluster node.',
            },
          ],
          hard: [
            {
              id: 'q3-hard-1',
              text: 'A Service shows `<none>` under ENDPOINTS. What is the most likely cause?',
              options: ['The Service port is wrong', 'The Service selector does not match any Pod labels', 'No nodes are available', 'The namespace is missing'],
              correctIndex: 1,
              explanation: 'When selectors do not match Pod labels, no Pods are registered.',
            },
            {
              id: 'q3-hard-2',
              text: 'Which Service type exposes the service on every node\'s IP at a static port?',
              options: ['ClusterIP', 'LoadBalancer', 'NodePort', 'ExternalName'],
              correctIndex: 2,
              explanation: 'NodePort allocates a port on every cluster node.',
            },
            {
              id: 'q3-hard-3',
              text: 'What is the purpose of `targetPort` in a Service spec?',
              options: ['The port clients use to reach the Service', 'The port the container actually listens on', 'The node port range', 'The namespace port'],
              correctIndex: 1,
              explanation: '`port` is what clients connect to; `targetPort` is what the container listens on.',
            },
          ],
        },
      },
      xpReward: 250,
      bossObjective: {
        title: 'Defeat the No-Endpoints Phantom',
        description: 'Write a Service YAML that selects Pods with label `app: backend` and routes port 80 to container port 3000.',
        completionCondition: 'quest_complete',
        victoryText: 'Endpoints populated! The Phantom vanishes into the routing table.',
      },
      skills: ['services', 'networking', 'label-selectors'],
    },
  ],
  skillTree: { nodes: [] },
  discoveries: [
    {
      id: 'discovery-pod-anatomy',
      title: 'Pod Anatomy',
      type: 'scroll',
      xpReward: 30,
      coinReward: 12,
      content: {
        type: 'code',
        code: `apiVersion: v1\nkind: Pod\nmetadata:\n  name: my-app\n  labels:\n    app: my-app\nspec:\n  containers:\n  - name: app\n    image: nginx:1.25\n    ports:\n    - containerPort: 80`,
        language: 'yaml',
        caption: 'A Pod is the smallest deployable unit. It wraps one or more containers that share network and storage.',
      },
    },
    {
      id: 'discovery-label-selectors',
      title: 'The Language of Labels',
      type: 'shrine',
      xpReward: 50,
      coinReward: 25,
      content: {
        type: 'text',
        text: 'Labels are key-value pairs attached to any Kubernetes object. Selectors filter objects by label. Services use selectors to find their Pods — a mismatch means no endpoints and no traffic routing.',
      },
    },
    {
      id: 'discovery-rolling-update',
      title: 'Treasure: Rolling Update',
      type: 'chest',
      xpReward: 40,
      coinReward: 20,
      content: {
        type: 'code',
        code: `strategy:\n  type: RollingUpdate\n  rollingUpdate:\n    maxSurge: 1\n    maxUnavailable: 0`,
        language: 'yaml',
        caption: 'Rolling updates replace Pods gradually, keeping the service available throughout. maxUnavailable: 0 ensures zero downtime.',
      },
    },
  ],
}
